Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\app\routes.py", line 27, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
Microblog startup
Exception on /explore [GET]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\app\routes.py", line 157, in explore
    posts = Post.query.order_by(*Post.timestamp.desc()).paginate(
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 434, in __getitem__
    return self.operate(getitem, index)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 861, in operate
    return op(self.comparator, *other, **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\operators.py", line 434, in __getitem__
    return self.operate(getitem, index)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\type_api.py", line 76, in operate
    return o[0](self.expr, op, *(other + o[1:]), **kwargs)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\default_comparator.py", line 177, in _getitem_impl
    _unsupported_impl(expr, op, other, **kw)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\sqlalchemy\sql\default_comparator.py", line 181, in _unsupported_impl
    raise NotImplementedError(
NotImplementedError: Operator 'getitem' is not supported on this expression
Microblog startup
