Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 872, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\app\routes.py", line 194, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\gabri\Desktop\Microblog\app\email.py", line 14, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\gabri\Desktop\Microblog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 1004, in quit
    res = self.docmd("quit")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
Microblog startup
Exception on /reset_password_request [POST]
Traceback (most recent call last):
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\gabri\Desktop\Microblog\app\routes.py", line 194, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\gabri\Desktop\Microblog\app\email.py", line 14, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\gabri\Desktop\Microblog\app\email.py", line 10, in send_email
    mail.send(msg)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\gabri\Desktop\Microblog\venv\lib\site-packages\flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2800.0_x64__qbz5n2kfra8p0\lib\smtplib.py", line 887, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Must issue a STARTTLS command first. l20sm2891oab.12 - gsmtp', 'email@email.com')
Microblog startup
Microblog startup
